title: suqin
subtitle: article
link: Homepage link
meta:
  description: null
  keywords:
    - 前端
    - suqin
  author: suqin
master:
  name: Your name
  about: Introduce yourself here
  email: Your E-mail
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: Copyrighter
  beginYear: 2011
  endYear: 2013
theme: default
codetheme: night
